import { StyleSheet, Dimensions } from "react-native";

let screenWidth = Dimensions.get('window').width;
let screenHeight = Dimensions.get('window').height;


export default StyleSheet.create({
    container:{
        flex:1,
        width:'100%',
    },
    linearGradient: {
        flex:1,
        width:'100%',
    },
    headerIcon:{
        justifyContent:'center',
        alignItems:'flex-start',
        position:'absolute',
        alignSelf:'center',
        marginLeft:10
    },
    header:{
        flex:0.1,
        width:'100%',
        flexDirection:'row',
        alignItems:'center',
        marginTop:10
    },
    v_main:{
        flex:0.6,
        width:screenWidth,
        alignItems:'center',
        marginTop:100
        
    },
    v_headerText:{
        alignItems:'center',
        justifyContent:'center',
        width:screenWidth
    },
    v_headerIconLeft:{
        alignItems:'center',
        justifyContent:'flex-start',
        width:'15%'
    },
    v_headerIconRight:{
        alignItems:'center',
        justifyContent:'flex-end',
        width:'15%'
    },
    headerText:{
        fontSize:18,
        color:'#fff',
        fontWeight:'bold',
        textAlign:'center'
    },
    headerBarIcon:{
        color:'#fff'
    },
    t_headerText:{
        color:'#fff',
        fontSize:18,
        fontWeight:'bold',
        alignItems:'center',
        textAlign:'center'
    },
    v_textBox:{
        borderWidth:1,
        borderColor:'#fff',
        borderRadius:15,
        marginTop:30,
        width:screenWidth-50,
        backgroundColor:'#fff',
    },
    v_input:{
        flexDirection:'row', 
        width:screenWidth-50, 
        justifyContent:'center', 
        alignItems:'center',
        borderBottomColor:'#0049b1',
        borderBottomWidth:1,
    },
    inputType1:{
        color:'#335755',
        fontSize:13,
        width:screenWidth-185,
        marginLeft:25,
    },
    inputType2:{
        color:'#335755',
        fontSize:13,
        width:screenWidth-185,
        marginLeft:10,

    },
    iconType1:{
        color:'#0049b1',
        marginHorizontal:5,
        alignItems:'center',
        justifyContent:'center', 
    },
    b_buttonType1:{
        paddingHorizontal:20,
        paddingVertical:12,
        backgroundColor:'#0049b1',
        color:'#fff',
        fontSize:16
    },
    b_buttonType2:{
        marginLeft:20,
        paddingHorizontal:20,
        paddingVertical:12,
        backgroundColor:'#0049b1',
        color:'#fff',
        fontSize:16

    },
    b_buttonType3:{
        marginLeft:20,
        paddingHorizontal:100,
        paddingVertical:12,
        backgroundColor:'#0049b1',
        color:'#fff',
        fontSize:16
    },
    v_news:{
        flex:0.3,
        justifyContent:'center',
        alignItems:'center'
    },
    mainIconUser:{
        color:'#fff',
        marginTop:15,
    },
    t_mainTextType1:{
        fontSize:20,
        fontWeight:'bold',
        color:'#fff',
        marginTop:10,
        marginLeft:10,
    },
    t_mainTextType2:{
        fontSize:17,
        color:'#fff',
        marginTop:5

    },
});